### ISSUE TITLE
If linearGradient angle == TWO_PI the gradient will be fully opaque

### ISSUE THREAD

**Issue by mheesakkers** [micycle1/PeasyGradients#10]
I hope you don't find these small issues annoying... I came across a minor bug I think. When you give the gradient an angle of TWO_PI the gradient will be opaque (first colorstop).

```
peasyGradients.linearGradient(gradient, TWO_PI);
```

**Angle == TWO_PI**
![Screenshot 2022-09-18 at 13 12 05](https://user-images.githubusercontent.com/5702106/190899215-84936099-8efe-4560-93fc-d7a702270d2f.png)

**versus angle == PI**
![Screenshot 2022-09-18 at 13 13 19](https://user-images.githubusercontent.com/5702106/190899285-957e0808-8600-498b-807b-3007cb40a655.png)

**Comment by micycle1** [comment]
Interesting find... I'll look into it.
