### ISSUE TITLE
Can this work with PDF export?

### ISSUE THREAD

**Issue by dkyy** [micycle1/PeasyGradients#14]
Is there any way to get the gradients work with PDF export?

I'm setting the target to my PGraphics object
```
PGraphics pg = createGraphics( myWidth, myHeight, PDF, "myFile.pdf");

peasyGradients.setRenderTarget( pg);
peasyGradients.linearGradient(blackToWhite, 0); 
```
But when I draw the gradient  I get this error:

`RuntimeException: No loadPixels() for PGraphicsPDF
`

**Comment by micycle1** [comment]
I don't think `PGraphicsPDF` supports pixel-based operations. It's mainly for drawing geometry primitives a .svgs (e.g. circles).
I've never used the PDF feature before, but I'd image you'd have to create a PGraphics having a normal render and then write that (essentially an image) to second PGraphics which would be your pdf one.
