### ISSUE TITLE
Visual glitch in gradients when using transparency + transparency is other way around

### ISSUE THREAD

**Issue by mheesakkers** [micycle1/PeasyGradients#7]
Hi Micycle! Loving this library and testing it out to the max ;)

I came across something when I was trying out transparency. It seems the transparency values are reversed, so if I want one of the two colors to have 0% opacity I actually have to set the solid color to 0% alpha for it to work.  I also came across a visual bug where the should be 0% alpha is being drawn in 100% alpha at the start of the drawing. This is especially noticable in the radial gradient drawing method. 

**See example screenshots:**
![Screenshot 2022-06-03 at 14 33 20](https://user-images.githubusercontent.com/5702106/171855112-38961206-ff08-4383-b15b-05a5c401f995.png)
![Screenshot 2022-06-03 at 14 33 06](https://user-images.githubusercontent.com/5702106/171855131-e40f1a09-6c33-4029-960d-555580522d42.png)

**Code:**
```
PeasyGradients peasyGradients;
PGraphics layer;

void setup() {
  size(512, 512);  
  peasyGradients = new PeasyGradients(this);
  
  Gradient gradient = new Gradient(
    color(#F4989C, 255), // salmon pink - should be fully opaque but isn't
    color(#279AF1, 0) // dodger blue - shouldn't be fully opaque but is
  );
  
  layer = createGraphics(width - 20, height -20);
  
  peasyGradients.setRenderTarget(layer);
  peasyGradients.radialGradient(
   gradient, 
   new PVector(layer.width * 0.5, layer.height * 0.5), 
   0.75
  );
  
  //peasyGradients.linearGradient(
  //  gradient, 
  //  0
  //);
   
  background(#ffffff);
  image(layer, 10, 10);
}

```

**Comment by micycle1** [comment]
I''ve just pushed a fix for this. Thanks for identifying it!

**Comment by mheesakkers** [comment]
@micycle1 the latest .jar release is from november 2021, where can I find the new release? 😇

**Comment by micycle1** [comment]
Jar artifacts are built for every commit by one of the github actions. You can find the built jar by clicking into one of the builds. The latest is at https://github.com/micycle1/PeasyGradients/actions/runs/2436028262.
