### ISSUE TITLE
Noticeable repetition by certain PGraphics sizes & gradient angle

### ISSUE THREAD

**Issue by mheesakkers** [micycle1/PeasyGradients#8]
Trying to generate a linear gradient where the width is substantially larger than its height and the angle is HALF_PI produces a noticeable repetition in rendering.

See screenshot:
![Screenshot 2022-09-18 at 09 46 35](https://user-images.githubusercontent.com/5702106/190891848-1cdd2a70-2835-4285-8126-71aefe00e639.png)

**Code to reproduce:**
```
size(540, 540, P2D);

PeasyGradients peasyGradients = new PeasyGradients(this);

Gradient gradient = new Gradient(
	color(#2660A4),
	color(#ffffff)
);

PGraphics gradientFill = createGraphics(320, 48);
peasyGradients.setRenderTarget(gradientFill);
peasyGradients.linearGradient(
	gradient,
	HALF_PI
);

background(#ffffff);
translate(width * 0.5, height * 0.5);
imageMode(CENTER);
image(gradientFill, 0, 0);
```

**Comment by micycle1** [comment]
Were you using the [0.9.1](https://github.com/micycle1/PeasyGradients/releases/tag/0.9.1) release? 

This has made me realise that it's quite old and a new version should be posted -- use [0.9.2](https://github.com/micycle1/PeasyGradients/releases/tag/0.9.2) which fixes the issue.

**Comment by mheesakkers** [comment]
Yes I was using the 0.9.1 release. Smooth gradient in [0.9.2](https://github.com/micycle1/PeasyGradients/releases/tag/0.9.2)!

**Comment by mheesakkers** [comment]
With some further testing and with slightly different parameters I still can reproduce the repetition. It happens when the width is far more smaller than the height.

**See example:**
![Screenshot 2022-09-21 at 08 29 44](https://user-images.githubusercontent.com/5702106/191430863-aa4419e8-72f6-4942-bcb6-7bdf52228561.png)

**Code:**
```
size(540, 540, P2D);

PeasyGradients peasyGradients = new PeasyGradients(this);

Gradient gradient = new Gradient(
	color(#2660A4),
	color(#ffffff)
);
gradient.setColorSpace(ColorSpaces.DIN99);

PGraphics gradientFill = createGraphics(16, 320);
peasyGradients.setRenderTarget(gradientFill);
peasyGradients.linearGradient(
	gradient,
	PI
);

background(#ffffff);
translate(width * 0.5, height * 0.5);
imageMode(CENTER);
image(gradientFill, 0, 0);
```
