### ISSUE TITLE
Visual glitches with certain colors

### ISSUE THREAD

**Issue by mheesakkers** [micycle1/PeasyGradients#9]
I was testing your library on one of my color palettes and noticed that when I choose a red color the interpolation goes wrong. See screenshot:
![Screenshot 2022-09-18 at 10 13 05](https://user-images.githubusercontent.com/5702106/190892629-1718d6fa-0a27-460f-9a48-9a2d40062581.png)

In the code below I tried to pin point the error by using mouseX to test different hues and this glitch appears on several color hues.

**Code to reproduce**
```
PeasyGradients peasyGradients;
color colorStop;

void setup() {
	size(540, 540, P2D);
	colorMode(HSB, 360, 100, 100);
	peasyGradients = new PeasyGradients(this);
}

void draw () {
	// colorStop = #2660A4; // produces normal result
	colorStop = #DA5552; // produces glitch
	// colorStop = color(floor(map(mouseX, 0, width, 0, 360)), 100, 100);

	Gradient gradient = new Gradient(colorStop, #ffffff);

	PGraphics gradientFill = createGraphics(320, 320);
	peasyGradients.setRenderTarget(gradientFill);
	peasyGradients.linearGradient(
		gradient,
		HALF_PI
	);

	background(#ffffff);
	
	// Draw gradient
	push();
	translate(width * 0.5, height * 0.5);
	imageMode(CENTER);
	image(gradientFill, 0, 0);
	pop();

	// Draw chose color stop
	fill(colorStop);
	rect(0, 0, 48, 48);

}
```

Example when I change the hue of the gradient:
![ezgif-1-38f7f35fbe](https://user-images.githubusercontent.com/5702106/190893005-26ad66bd-0178-425c-83cb-fbca38dbbfa1.gif)

**Comment by micycle1** [comment]
I believe this issue is from the color space values going out of bounds when being converted back into RGB, and it's something I very much know about -- in fact it's probably the biggest thing left to do.

In the meantime, you can change color space with this:
`gradient.setColorSpace(ColorSpaces.DIN99)` 

or use `.nextColSpace()` and `.prevColSpace()` to cycle through the color spaces.

**Comment by mheesakkers** [comment]
Colorspaces.DIN99 seems to fix the gradients of most hues. Thanks!
